import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod, // Minify in production for smaller bundle
	metafile: prod, // Generate metafile for bundle analysis
	outfile: "main.js",
});

if (prod) {
	const result = await context.rebuild();

	// Write metafile for bundle analysis
	if (result.metafile) {
		const fs = await import('fs');
		fs.writeFileSync('meta.json', JSON.stringify(result.metafile, null, 2));
		// console.log('\n Bundle analysis written to meta.json');
		// console.log('Output size:', (result.metafile.outputs['main.js'].bytes / 1024 / 1024).toFixed(2), 'MB');
	}

	process.exit(0);
} else {
	await context.watch();
}